#!/bin/bash
set -e

case "$1" in
  start)
        if pidof olsrd; then
            echo "OLSRD is already running!"
            exit 0
        fi
        rm -f /var/run/olsrd.pid
        echo "Starting OLSRD"
        start-stop-daemon --start --quiet --pidfile /var/run/olsrd.pid --exec /usr/sbin/olsrd -- -d 0 -f /etc/olsrd/olsrd.conf &
        while ! pidof olsrd > /dev/null ; do
          sleep 1
        done
        echo $(pidof olsrd) > /var/run/olsrd.pid
        ;;
  stop)
        if ! pidof olsrd; then
            echo "OLSRD is not running!"
            rm -f /var/run/olsrd.pid
            exit 0
        fi
        pidof olsrd  > /dev/null || exit 0
        echo "Stopping OLSRD"
        start-stop-daemon --stop --quiet --pidfile /var/run/olsrd.pid --exec /usr/sbin/olsrd
        sleep 1
        rm -f /var/run/olsrd.pid
        ;;
  restart)
        echo "Restarting OLSRD"
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: /etc/init.d/olsrd (start | stop | restart)" >&2
        exit 1
        ;;
esac
~          